Repository RAF-SI-2024/Banka-2-Frontend, pull requests merged in 2025-06, with the labels that each got.

#295 otp | confirmation code sent with api req
  src/components/payments/payment-new/NewPaymentForm.tsx
  src/types/bank_user/transaction.ts
Labels: size/XS, approved

#296 Issue #294: Order Page API Requests; Mocks Refactoring
  src/__mocks/ActuariesMock.ts
  src/__mocks/CurrencyMock.ts
  src/__mocks/OrdersMock.ts
  src/__mocks/PortfolioDataMock.ts
  src/__mocks/TaxesMock.ts
  src/__mocks/trading/GraphMock.ts
  src/__mocks/trading/SecurityListMock.ts
  src/api/exchange/order.ts
  src/components/actuary/ActuariesTable.tsx
  src/components/order-table/OrderListColumnDef.tsx
  src/components/order-table/OrderTable.tsx
  src/components/portfolio/PortfolioTable.tsx
  src/components/tax/TaxTable.tsx
  src/components/trading/SecurityInfiniteList.tsx
  src/components/trading/TradingViewChart.tsx
  src/mocks/mokdatasExchange.tsx
  src/pages/my-portfolio/MyPortfolioPage.tsx
  src/types/exchange/order.ts
Labels: approved, size/XL

#298 Issues #278, #279: Trading page
  index.html
  package.json
  pnpm-lock.yaml
  public/favicon.ico
  src/__mocks/trading/GraphMock.ts
  src/api/exchange/security.ts
  src/components/trading/SecurityFIlters.tsx
  src/components/trading/SecurityInfiniteList.tsx
  src/components/trading/SecurityListCard.tsx
  src/components/trading/SecurityListSingle.tsx
  src/components/trading/TradingViewChart.tsx
  src/components/trading/TradingViewChartFunctions.ts
  src/constants/endpoints.ts
  src/hooks/use-candle-data.ts
  src/pages/trading/Trading.tsx
  src/types/exchange/exchange.ts
  src/types/exchange/security.ts
Labels: approved, size/XL

#301 create order done
  src/components/trading/SecurityCreateOrder.tsx
  src/types/exchange/order.ts
Labels: approved

#302 Actuaries API Integration
  src/api/bank_user/actuary.ts
  src/api/bank_user/user.ts
  src/api/exchange/security.ts
  src/components/__common__/VerificationOTP.tsx
  src/components/__common__/sidebar/nav/main/AdminNavMainData.tsx
  src/components/__common__/sidebar/nav/main/EmployeeNavMainData.tsx
  src/components/actuary/ActuariesListColumnDef.tsx
  src/components/actuary/ActuariesTable.tsx
  src/components/actuary/edit-actuary/EditActuaryDialog.tsx
  src/components/actuary/edit-actuary/EditActuaryForm.tsx
  src/components/bank-account/bank-account-create/CreateBankAccount.tsx
  src/components/bank-account/bank-account-single/AdjustLimitsOTP.tsx
  src/components/bank-account/bank-account-single/BankAccountBalance.tsx
  src/components/bank-account/bank-account-single/BankAccountDetails.tsx
  src/components/trading/TradingViewChart.tsx
  src/hooks/sidebar/use-bank-accounts-data.ts
  src/pages/actuary/ActuaryDropDownMenu.tsx
  src/pages/bank-accounts-client/BankAccount.tsx
  src/router/routes.tsx
  src/types/bank_user/actuary.ts
  src/types/bank_user/user.ts
Labels: approved, size/XL

#303 my portfolio and apporve declie
  src/__mocks/trading/SecurityListMock.ts
  src/components/portfolio/PortfolioTable.tsx
  src/components/portfolio/PortfolioTableColumns.tsx
  src/components/trading/SecurityInfiniteList.tsx
  src/types/exchange/order.ts
Labels: approved
