Repository RAF-SI-2024/Banka-2-Frontend, pull requests merged in 2025-03, with the labels that each got.

#110 currency cherry
  src/components/createBankAccount/CreateBankAccount.tsx
  src/components/createBankAccount/CurrencySelect.tsx
Labels: size/L

#112 Create OWNERS
  OWNERS
Labels: size/XS

#113 Update OWNERS
  OWNERS
Labels: size/XS, approved

#111 Add new credit card button
  src/components/bank-account/BankAccountBalance.tsx
  src/components/bank-account/BankAccountCards.tsx
  src/components/bank-account/BankAccountDetails.tsx
  src/components/bank-account/BankAccountTransactions.tsx
  src/components/ui/card-swipe.tsx
  src/components/ui/credit-card.tsx
  src/pages/BankAccount.tsx
  src/pages/BankAccountList.tsx
  src/pages/UserList.tsx
Labels: size/L, approved, lgtm

#115 Odradjen OTP deo vezan za task 96 tj step one, dodat BankAccountDetai…
  package.json
  pnpm-lock.yaml
  src/components/bank-account/BankAccountDetails.tsx
  src/components/bank-account/BankAccountDetailsAdjustLimitsDialog.tsx
  src/components/ui/input-otp.tsx
Labels: size/L, approved, lgtm

#117 Card details page
  src/components/bank-account/BankAccountCards.tsx
  src/components/card/BankCard.tsx
  src/components/card/BankCardDetails.tsx
  src/pages/BankAccount.tsx
  src/pages/CardDetails.tsx
  src/router/routes.tsx
Labels: size/L, approved, lgtm

#121 sprint-3
  src/api/auth.ts
  src/components/bank-account/BankAccountDetails.tsx
  src/components/bank-account/BankAccountDetailsAdjustLimitsDialog.tsx
Labels: size/L, approved, lgtm

#118 Issue 97 finished.
  src/api/account.ts
  src/components/createBankAccount/ActivityCodeDropdown.tsx
  src/components/createBankAccount/CreateBankAccount.tsx
  src/components/createBankAccount/CurrencySelect.tsx
  src/components/createBankAccount/PlanSelect.tsx
  src/components/createBankAccount/TypeSelect.tsx
  src/types/acccount.ts
Labels: approved, lgtm, size/XL

#119 Added dialog for requesting new card. OTP input added
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/components/createCard/CreateCardDialog.tsx
  src/components/createCard/FailNotificationCard.tsx
  src/components/createCard/OTPForm.tsx
  src/components/createCard/SuccessNotificationCard.tsx
  src/components/ui/input-otp.tsx
Labels: size/L, approved, lgtm

#120 Block card button
  src/components/card/BankCardDetails.tsx
Labels: size/L, approved, lgtm

#122 Odradjen drugi deo taska za formu
  src/components/bank-account/BankAccountDetails.tsx
  src/components/bank-account/BankAccountDetailsAdjustLimitsDialog.tsx
Labels: approved, lgtm, size/S

#123 Create credit card automatically
  src/api/account.ts
  src/components/createBankAccount/ActivityCodeDropdown.tsx
  src/components/createBankAccount/CreateBankAccount.tsx
  src/components/createBankAccount/CurrencySelect.tsx
  src/components/createBankAccount/PlanSelect.tsx
  src/components/createBankAccount/TypeSelect.tsx
  src/types/acccount.ts
Labels: approved, lgtm, size/XL

#124 Card details page
  src/components/bank-account/BankAccountCards.tsx
  src/components/card/BankCard.tsx
  src/components/card/BankCardDetails.tsx
  src/pages/BankAccount.tsx
  src/pages/CardDetails.tsx
  src/router/routes.tsx
Labels: size/L, approved, lgtm

#125 Adjust bank account limit
  package.json
  pnpm-lock.yaml
  src/api/auth.ts
  src/components/bank-account/BankAccountDetails.tsx
  src/components/bank-account/BankAccountDetailsAdjustLimitsDialog.tsx
  src/components/ui/input-otp.tsx
Labels: size/L, approved, lgtm

#127 creating bank account (existing) - check if the account exists by email
  src/components/createBankAccount/CreateBankAccount.tsx
Labels: approved, lgtm, size/M

#141 Issue #137 - Display last name in NavUser
  src/components/common/sidebar/nav/user/NavUser.tsx
Labels: approved, lgtm, size/S

#144 Issue #143 GET Card info API call; Block card api call
  src/api/bankAccount.ts
  src/api/card.ts
  src/components/bank-account/BankAccountCards.tsx
  src/components/card/BankCard.tsx
  src/components/card/BankCardDetails.tsx
  src/components/ui/credit-card.tsx
  src/pages/Card.tsx
  src/types/cardDTO.ts
Labels: size/L, approved, lgtm

#145 Creating card api request works
  src/components/createBankAccount/CreateBankAccount.tsx
  src/components/createBankAccount/TypeSelect.tsx
Labels: approved, lgtm, size/M

#146 Sprint3nikola
  src/components/createBankAccount/CreateBankAccount.tsx
  src/components/createBankAccount/TypeSelect.tsx
Labels: approved, lgtm, size/M

#149 account list pagination and actions button for activate/deactivate
  src/api/bankAccount.ts
  src/components/allBankingAccounts/BankingAccountDropdownMenu.tsx
  src/components/allBankingAccounts/BankingAccountsColumnDef.tsx
  src/components/allBankingAccounts/BankingAccountsTable.tsx
  src/components/createBankAccount/CreateBankAccount.tsx
Labels: approved, lgtm, size/M

#150 Issue #135: Card create (CLIENT)
  src/api/card.ts
  src/api/currency.ts
  src/components/bank-account/BankAccountCards.tsx
  src/components/card/BankCard.tsx
  src/components/card/BankCardDetails.tsx
  src/components/createCard/CreateCardDialog.tsx
  src/components/createCard/CreateCardForm.tsx
  src/components/createCard/OTPForm.tsx
  src/pages/BankAccount.tsx
  src/pages/Card.tsx
  src/types/card.ts
Labels: size/L, approved, lgtm

#151 Issue #130: Get account cards
  src/api/bankAccount.ts
  src/components/bank-account/BankAccountCards.tsx
  src/components/common/Footer.tsx
  src/hooks/sidebar/use-bank-accounts-data.ts
  src/pages/BankAccount.tsx
Labels: size/L, approved, lgtm

#152 Credit cards expandable table inside accounts and activate/deactivate
  src/api/bankAccount.ts
  src/api/card.ts
  src/components/allBankingAccounts/BankingAccountDropdownMenu.tsx
  src/components/allBankingAccounts/BankingAccountsColumnDef.tsx
  src/components/allBankingAccounts/BankingAccountsTable.tsx
  src/components/allBankingAccounts/CreditCardDropdownMenu.tsx
  src/components/card/BankCardDetails.tsx
Labels: approved, lgtm, size/XL

#153 Issue #132: Edit account limits
  src/api/bankAccount.ts
  src/components/bank-account/AdjustLimitsForm.tsx
  src/components/bank-account/AdjustLimitsOTP.tsx
  src/components/bank-account/BankAccountDetails.tsx
  src/components/bank-account/BankAccountDetailsAdjustLimitsDialog.tsx
  src/components/card/BankCardDetails.tsx
  src/components/createCard/CreateCardDialog.tsx
  src/components/createCard/CreateCardForm.tsx
  src/types/bankAccount.ts
Labels: size/L, approved, lgtm

#154 Create Bank account fixed bugs
  src/components/createBankAccount/CreateBankAccount.tsx
  src/components/createBankAccount/CreateBankAccountDialog.tsx
  src/components/createBankAccount/CurrencySelect.tsx
  src/context/AuthContext.tsx
Labels: approved, lgtm, size/M

#155 Issue #129: Forgot password fix
  src/components/passwordReset/ResetPassForm.tsx
Labels: approved, lgtm, size/S

#156 Sprint 3 done
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/api/account.ts
  src/api/auth.ts
  src/api/bankAccount.ts
  src/api/card.ts
  src/api/currency.ts
  src/api/user.ts
  src/components/allBankingAccounts/BankingAccountDropdownMenu.tsx
  src/components/allBankingAccounts/BankingAccountsColumnDef.tsx
  src/components/allBankingAccounts/BankingAccountsTable.tsx
  src/components/allBankingAccounts/CreditCardDropdownMenu.tsx
  src/components/bank-account/AdjustLimitsForm.tsx
  src/components/bank-account/AdjustLimitsOTP.tsx
  src/components/bank-account/BankAccountCards.tsx
  src/components/bank-account/BankAccountDetails.tsx
  src/components/bank-account/BankAccountDetailsAdjustLimitsDialog.tsx
  src/components/card/BankCard.tsx
  src/components/card/BankCardDetails.tsx
  src/components/common/Footer.tsx
  src/components/common/sidebar/nav/user/NavUser.tsx
  src/components/createBankAccount/ActivityCodeDropdown.tsx
  src/components/createBankAccount/CreateBankAccount.tsx
  src/components/createBankAccount/CreateBankAccountDialog.tsx
  src/components/createBankAccount/CurrencySelect.tsx
  src/components/createBankAccount/PlanSelect.tsx
  src/components/createBankAccount/TypeSelect.tsx
  src/components/createCard/CreateCardDialog.tsx
  src/components/createCard/CreateCardForm.tsx
  src/components/createCard/FailNotificationCard.tsx
  src/components/createCard/OTPForm.tsx
  src/components/createCard/SuccessNotificationCard.tsx
  src/components/passwordReset/ResetPassForm.tsx
  src/components/ui/card-swipe.tsx
  src/components/ui/credit-card.tsx
  src/components/ui/input-otp.tsx
  src/context/AuthContext.tsx
  src/hooks/sidebar/use-bank-accounts-data.ts
  src/pages/BankAccount.tsx
  src/pages/Card.tsx
  src/router/routes.tsx
  src/types/acccount.ts
  src/types/bankAccount.ts
  src/types/card.ts
Labels: approved, lgtm, size/XXL

#166 Issue #160 & more: Account rename validation. MoneyInput.
  src/assets/PiggyBank.tsx
  src/assets/Wallet.tsx
  src/components/bank-account/AdjustLimitsForm.tsx
  src/components/bank-account/BankAccountBalance.tsx
  src/components/bank-account/BankAccountCards.tsx
  src/components/bank-account/BankAccountDetails.tsx
  src/components/bank-account/BankAccountDetailsAdjustLimitsDialog.tsx
  src/components/card/BankCardDetails.tsx
  src/components/card/BankCardDisplay.tsx
  src/components/common/Footer.tsx
  src/components/common/VerificationOTP.tsx
  src/components/common/input/MoneyInput.tsx
  src/components/common/input/NumberInput.tsx
  src/components/common/sidebar/nav/main/NavMain.tsx
  src/components/createCard/CreateCardDialog.tsx
  src/components/createCard/OTPSuccessNotifiaction.tsx
  src/components/home/BalanceCard.tsx
  src/components/home/ConverterCard.tsx
  src/components/passwordChange/PasswordChangeDialog.tsx
  src/components/ui/credit-card.tsx
  src/components/ui/sonner.tsx
  src/hooks/sidebar/use-bank-accounts-data.ts
  src/index.css
  src/pages/BankAccount.tsx
  src/pages/BankCard.tsx
  src/router/routes.tsx
  src/utils/format-currency.ts
  src/utils/format-number.ts
Labels: approved, lgtm, size/XXL

#169 Issue #168: Swap ErrorAlert with sonner (Toaster)
  src/components/admin/EditUserForm.tsx
  src/components/allBankingAccounts/BankingAccountDropdownMenu.tsx
  src/components/bank-account/BankAccountDetailsAdjustLimitsDialog.tsx
  src/components/card/BankCardDetails.tsx
  src/components/common/VerificationOTP.tsx
  src/components/common/header/HeaderWithLogo.tsx
  src/components/createCard/CreateCardDialog.tsx
  src/components/login/LoginForm.tsx
  src/components/passwordChange/ConfirmCurrentPassword.tsx
  src/components/passwordChange/PasswordChangeDialog.tsx
  src/components/passwordReset/ResetPassForm.tsx
  src/components/passwordReset/ResetPassReqForm.tsx
  src/components/register/RegisterDialog.tsx
  src/components/register/RegisterDialogContent.tsx
  src/components/register/RegisterPasswordForm.tsx
  src/components/register/RegisterRequests.tsx
  src/components/register/client/RegisterFormSecondClient.tsx
  src/components/register/employee/RegisterFormSecondEmployee.tsx
  src/components/ui/sonner.tsx
  src/layouts/AuthorizationLayout.tsx
  src/pages/BankAccount.tsx
  src/pages/BankAccountList.tsx
  src/pages/BankCard.tsx
  src/pages/Card.tsx
  src/pages/ComponentShowcase.tsx
  src/pages/Home.tsx
  src/pages/UserList.tsx
  src/utils/show-toast-utils.tsx
Labels: approved, lgtm

#171 Issue #167: Switch to MoneyInput where needed
  src/components/allBankingAccounts/CreditCardDropdownMenu.tsx
  src/components/bank-account/AdjustLimitsForm.tsx
  src/components/bank-account/BankAccountBalance.tsx
  src/components/bank-account/BankAccountDetails.tsx
  src/components/bank-account/BankAccountDetailsAdjustLimitsDialog.tsx
  src/components/common/input/MoneyInput.tsx
  src/components/createCard/CreateCardDialog.tsx
  src/components/createCard/CreateCardForm.tsx
Labels: approved, lgtm, size/XL

#173 added icon for transfers
  src/components/common/sidebar/nav/main/ClientNavMainData.tsx
Labels: approved, lgtm

#174 Setting 'currencies' fixed. Backend changed response.
  src/components/createBankAccount/CreateBankAccount.tsx
  src/context/AuthContext.tsx
Labels: size/XS, approved, lgtm

#183 Cypress and sidebar
  cypress.config.ts
  cypress/e2e/admin-example/search_user.cy.ts
  cypress/e2e/admin-example/test.cy.ts
  cypress/e2e/client-test.cy.ts
  cypress/e2e/login.cy.ts
  cypress/e2e/register_new_client.cy.ts
  cypress/fixtures/example.json
  cypress/support/commands.ts
  cypress/support/component-index.html
  cypress/support/component.js
  cypress/support/e2e.ts
  cypress/support/index.d.ts
  cypress/tsconfig.json
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/api/card.ts
  src/api/currency.ts
  src/components/bank-account/BankAccountCards.tsx
  src/components/common/sidebar/nav/main/ClientNavMainData.tsx
  src/components/createCard/CreateCardDialog.tsx
  src/hooks/sidebar/use-bank-accounts-data.ts
  src/hooks/sidebar/use-credit-cards-data.ts
  src/router/routes.tsx
  tsconfig.json
Labels: approved, size/XXL

#185 Fix create bank account
  src/components/createBankAccount/CreateBankAccount.tsx
Labels: approved, lgtm, size/M

#186 Sprint 4 prep
  cypress.config.ts
  cypress/e2e/admin-example/search_user.cy.ts
  cypress/e2e/admin-example/test.cy.ts
  cypress/e2e/client-test.cy.ts
  cypress/e2e/login.cy.ts
  cypress/e2e/register_new_client.cy.ts
  cypress/fixtures/example.json
  cypress/support/commands.ts
  cypress/support/component-index.html
  cypress/support/component.js
  cypress/support/e2e.ts
  cypress/support/index.d.ts
  cypress/tsconfig.json
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/api/card.ts
  src/api/currency.ts
  src/components/bank-account/BankAccountCards.tsx
  src/components/common/sidebar/nav/main/ClientNavMainData.tsx
  src/components/createBankAccount/CreateBankAccount.tsx
  src/components/createCard/CreateCardDialog.tsx
  src/hooks/sidebar/use-bank-accounts-data.ts
  src/hooks/sidebar/use-credit-cards-data.ts
  src/router/routes.tsx
  tsconfig.json
Labels: approved, lgtm, size/XXL

#187 Cypress test improvement
  cypress/e2e/login.cy.ts
  cypress/e2e/register_new_client.cy.ts
  cypress/support/commands.ts
Labels: size/L, approved, lgtm

#188 Cypress tests
  cypress/e2e/admin-example/search_user.cy.ts
  cypress/e2e/admin-example/test.cy.ts
  cypress/e2e/client-test.cy.ts
  cypress/e2e/login.cy.ts
  cypress/e2e/register_new_client.cy.ts
Labels: size/L, approved, lgtm

#191 Loan request page for employee
  src/api/loan.ts
  src/components/common/sidebar/nav/main/EmployeeNavMainData.tsx
  src/components/createBankAccount/CreateBankAccount.tsx
  src/context/AuthContext.tsx
  src/pages/LoanRequestList.tsx
  src/router/routes.tsx
  src/router/utils/ProtectedRoutes.tsx
Labels: approved, lgtm

#194 expandable row
  src/components/allBankingAccounts/BankingAccountsTable.tsx
  src/components/allBankingAccounts/ExpandableDataTable.tsx
Labels: size/L, approved, lgtm

#202 All Loans page created. Waiting for backend to resolve "outstanding debt" problem.
  src/api/loan.ts
  src/components/common/sidebar/nav/main/EmployeeNavMainData.tsx
  src/components/loans/allLoans/AllLoanListColumnDef.tsx
  src/components/loans/allLoans/AllLoanTable.tsx
  src/components/loans/request/LoanDropdownMenu.tsx
  src/components/loans/request/LoanListColumnDef.tsx
  src/components/loans/request/LoanRequestTable.tsx
  src/pages/AllLoanList.tsx
  src/pages/LoanRequestList.tsx
  src/router/routes.tsx
  src/types/loanType.ts
Labels: approved, lgtm

#203 Guards | Unauthorized
  eslint.config.js
  src/api/axios.ts
  src/context/AuthContext.tsx
  src/types/auth.ts
Labels: approved, lgtm, size/M

#201 Sprit4 fixed
  src/api/currency.ts
  src/api/templates.ts
  src/components/home/AddTemplateDialog.tsx
  src/components/home/ConverterCard.tsx
  src/components/home/DeleteConfirmationDialog.tsx
  src/components/home/EditTemplateDialog.tsx
  src/components/home/QuickPaymentCard.tsx
  src/components/home/TemplateDropDownMenu.tsx
  src/types/templates.ts
Labels: approved, lgtm, size/XL

#196 Odradjen task 162 ceo
  src/api/currency.ts
  src/api/transactions.ts
  src/pages/TransferPage.tsx
  src/router/routes.tsx
  src/types/transaction.ts
  src/types/transfers.ts
Labels: size/L, approved, lgtm

#208 Client LoanOverview table, Employee RequestLoan table, Employee AllLoans table, Added Client routes guard
  src/api/loan.ts
  src/components/common/sidebar/nav/main/EmployeeNavMainData.tsx
  src/components/loans/client/LoanOverviewDropdownMenu.tsx
  src/components/loans/client/LoanOverviewListColumnDef.tsx
  src/components/loans/client/LoanOverviewTable.tsx
  src/components/loans/employee/allLoansTable/AllLoanListColumnDef.tsx
  src/components/loans/employee/allLoansTable/AllLoanTable.tsx
  src/components/loans/employee/requestTable/LoanDropdownMenu.tsx
  src/components/loans/employee/requestTable/LoanListColumnDef.tsx
  src/components/loans/employee/requestTable/LoanRequestTable.tsx
  src/components/ui/badge.tsx
  src/pages/AllLoanList.tsx
  src/pages/LoanOverviewList.tsx
  src/pages/LoanRequestList.tsx
  src/router/routes.tsx
  src/router/utils/ProtectedRoutes.tsx
  src/types/loan.ts
Labels: approved, lgtm, size/XL

#206 Sprint 4
  package-lock.json
  src/api/bankAccount.ts
  src/components/bank-account/BankAccountTransactions.tsx
  src/components/bank-account/TransactionsDataTable.tsx
  src/components/bank-account/TransactionsDataTableColumnDef.tsx
  src/components/home/RecentTransactions.tsx
  src/pages/BankAccount.tsx
  src/pages/BankCard.tsx
  src/pages/Card.tsx
  src/pages/TransactionsOverview.tsx
  src/router/routes.tsx
  src/types/bankAccount.ts
  src/types/bankAccountType.ts
  src/types/enums.ts
  src/types/transaction.ts
Labels: size/L, approved, lgtm

#209 Guards | Redirect to /home if route does not exist
  src/router/routes.tsx
Labels: size/XS, approved, lgtm

#210 popravljen task 161
  src/components/newPayment/AddRecipientTemplate.tsx
  src/components/newPayment/AmountInput.tsx
  src/components/newPayment/RecipientInput.tsx
  src/pages/NewPayment.tsx
Labels: size/L, approved, lgtm

#213 Added filters and changed colors of Amounts
  .gitignore
  src/components/bank-account/TransactionsDataTable.tsx
  src/components/bank-account/TransactionsDataTableColumnDef.tsx
  src/components/home/RecentTransactions.tsx
  src/utils/format-currency.ts
Labels: size/L, approved, lgtm

#212 Styling improvements: New transfer/exchange
  cypress/e2e/employee/scenario1.cy.ts
  cypress/support/commands/employee/bank-account-list.ts
  index.html
  src/api/loan.ts
  src/components/loans/client/LoanOverviewListColumnDef.tsx
  src/components/loans/employee/allLoansTable/AllLoanListColumnDef.tsx
  src/components/loans/loanDetailsClient/LoanDetailsClientBankAccount.tsx
  src/components/loans/loanDetailsClient/LoanDetailsClientLeft.tsx
  src/components/loans/loanDetailsClient/LoanDetailsClientLoan.tsx
  src/components/loans/loanDetailsClient/LoanDetailsClientRight.tsx
  src/components/loans/newLoanRequest/LoanRequestForm.tsx
  src/components/newPayment/AddRecipientTemplate.tsx
  src/components/newPayment/NewPaymentForm.tsx
  src/components/newPayment/RecipientInput.tsx
  src/components/newTransfer/NewTransferForm.tsx
  src/components/newTransfer/NewTransfertFormDef.tsx
  src/pages/LoanDetailsClient.tsx
  src/pages/TransferPage.tsx
  src/types/loan.ts
Labels: bug, approved, lgtm, styling, size/XXL

#215 Added Data picker for filtering with Data Range Picker
  src/components/bank-account/TransactionsDataTable.tsx
  src/components/bank-account/TransactionsDataTableColumnDef.tsx
  src/components/ui/date-range-picker.tsx
Labels: approved, lgtm

#216 Issue #179: Loan Details (Client)
  src/api/loan.ts
  src/api/transactionCode.ts
  src/components/allBankingAccounts/BankingAccountsColumnDef.tsx
  src/components/allBankingAccounts/ExpandableDataTable.tsx
  src/components/common/datatable/DataTableViewOptions.tsx
  src/components/home/ConverterCard.tsx
  src/components/loans/client/LoanOverviewListColumnDef.tsx
  src/components/loans/client/LoanOverviewTable.tsx
  src/components/loans/employee/allLoansTable/AllLoanListColumnDef.tsx
  src/components/loans/employee/allLoansTable/AllLoanTable.tsx
  src/components/loans/employee/requestTable/LoanListColumnDef.tsx
  src/components/loans/employee/requestTable/LoanRequestTable.tsx
  src/components/loans/loanDetailsClient/InstallmentList.tsx
  src/components/loans/loanDetailsClient/InstallmentTableColumnDef.tsx
  src/components/loans/loanDetailsClient/LoanDetailsClientLeft.tsx
  src/components/loans/loanDetailsClient/LoanDetailsClientLoan.tsx
  src/components/loans/loanDetailsClient/LoanDetailsClientRight.tsx
  src/components/newPayment/NewPaymentForm.tsx
  src/components/ui/badge.tsx
  src/index.css
  src/pages/LoanDetailsClient.tsx
  src/types/loan.ts
  src/utils/format-number.ts
Labels: size/L, approved, lgtm

#218 Issue #217: exchange rate list
  src/api/exchange.ts
  src/components/exchangeRateList/ExchangeRateListTable.tsx
  src/components/loans/client/LoanOverviewTable.tsx
  src/components/loans/loanDetailsClient/LoanDetailsClientLeft.tsx
  src/components/loans/loanDetailsClient/LoanDetailsClientRight.tsx
  src/pages/ExchangeRateList.tsx
  src/pages/LoanOverviewList.tsx
  src/router/routes.tsx
  src/types/exchange.ts
  src/utils/format-currency.ts
  src/utils/format-number.ts
Labels: size/L, approved, lgtm

#219 recent transactions
  src/api/bankAccount.ts
  src/api/card.ts
  src/api/templates.ts
  src/components/home/ConverterCard.tsx
  src/components/home/RecentTransactions.tsx
Labels: approved, lgtm

#220 Transaction tables
  src/components/bank-account/TransactionsDataTable.tsx
  src/components/bank-account/TransactionsDataTableColumnDef.tsx
  src/components/home/RecentTransactions.tsx
  src/components/login/LoginForm.tsx
  src/types/transaction.ts
Labels: size/L, approved, lgtm

#221 Transaction table - Show actual data
  src/api/bankAccount.ts
  src/api/transactions.ts
  src/components/bank-account/BankAccountTransactions.tsx
  src/components/bank-account/TransactionsDataTable.tsx
  src/components/bank-account/TransactionsDataTableColumnDef.tsx
  src/components/home/RecentTransactions.tsx
  src/components/ui/date-range-picker.tsx
  src/pages/BankAccount.tsx
  src/pages/TransactionsOverview.tsx
  src/types/enums.ts
  src/types/transaction.ts
  src/utils/transactions-table-utils.tsx
Labels: approved, lgtm, size/XXL

#223 fix
  src/api/transactionCode.ts
  src/components/newPayment/NewPaymentForm.tsx
Labels: approved

#224 table transactions fix
  src/api/transactionCode.ts
  src/types/transaction.ts
  src/utils/transactions-table-utils.tsx
Labels: approved

#233 Update Admin sidebar
  src/components/__common__/sidebar/nav/main/AdminNavMainData.tsx
  src/components/__common__/sidebar/nav/main/EmployeeNavMainData.tsx
  src/router/routes.tsx
  src/router/utils/ProtectedRoutes.tsx
Labels: approved, lgtm, size/M

#235 Fix employee guard. Add titles where missing
  src/pages/bank-accounts-employee/BankAccountList.tsx
  src/pages/client-list/ClientList.tsx
  src/pages/loans-employee/AllLoanList.tsx
  src/pages/loans-employee/LoanRequestList.tsx
  src/pages/user-list/UserList.tsx
  src/router/routes.tsx
Labels: approved, lgtm, size/S

#237 Milica maticc sprint 5
  package-lock.json
  src/api/actuary.ts
  src/components/__common__/sidebar/nav/main/AdminNavMainData.tsx
  src/components/__common__/sidebar/nav/main/EmployeeNavMainData.tsx
  src/components/actuary/ActuariesListColumnDef.tsx
  src/components/actuary/ActuariesTable.tsx
  src/components/auth/login/LoginForm.tsx
  src/components/bank-account/bank-account-single/BankAccountCards.tsx
  src/components/card/card-single/BankCard.tsx
  src/components/card/card-single/BankCardDetails.tsx
  src/pages/CardDetails.tsx
  src/pages/actuary/ActuaryDropDownMenu.tsx
  src/pages/actuary/ActuaryListPage.tsx
  src/pages/bank-accounts-client/BankAccount.tsx
  src/router/routes.tsx
  src/types/actuary.ts
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
Labels: approved, lgtm, size/XXL

#238 sprint-5, ostalo je da se uveze dijalog za reset i popravke za edit
  src/__mocks/mock-actuaries.ts
  src/components/__common__/sidebar/AppSidebar.tsx
  src/components/__common__/sidebar/nav/main/EmployeeNavMainData.tsx
  src/components/actuary/ActuariesListColumnDef.tsx
  src/components/actuary/ActuariesTable.tsx
  src/components/actuary/edit-actuary/ActuaryFieldRenderer.tsx
  src/components/actuary/edit-actuary/EditActuaryDialog.tsx
  src/components/actuary/edit-actuary/EditActuaryForm.tsx
  src/components/actuary/reset-used-limit/ResetLimitConfirmDialog.tsx
  src/components/auth/login/LoginForm.tsx
  src/pages/actuary/ActuaryDropDownMenu.tsx
  src/pages/actuary/ActuaryListPage.tsx
  src/pages/bank-accounts-employee/BankAccountList.tsx
  src/types/actuary.ts
Labels: approved, lgtm, size/XL

#239 EditActuary( 3.1.1.1 Admin ) and 3.1.2( Reset used limit ) done
  src/api/actuary.ts
  src/components/actuary/ActuariesListColumnDef.tsx
  src/components/actuary/ActuariesTable.tsx
  src/components/actuary/edit-actuary/EditActuaryDialog.tsx
  src/components/actuary/edit-actuary/EditActuaryForm.tsx
  src/pages/actuary/ActuaryDropDownMenu.tsx
Labels: approved, lgtm, size/XL

#240 Bug fixed
  src/components/bank-account/bank-account-single/TransactionsDataTable.tsx
  src/components/bank-account/bank-account-table/BankingAccountsTable.tsx
  src/components/loans/employee/allLoansTable/AllLoanTable.tsx
  src/components/loans/employee/requestTable/LoanRequestTable.tsx
  src/components/user-table/all-users/UserTable.tsx
  src/components/user-table/clients/ClientTable.tsx
Labels: size/XS, approved, lgtm

#243 fixed code arhitecture and design for order table
  src/components/loans/employee/allLoansTable/AllLoanTable.tsx
  src/components/order-table/OrderActionMenu.tsx
  src/components/order-table/OrderDropdownMenu.tsx
  src/components/order-table/OrderListColumnDef.tsx
  src/components/order-table/OrderTable.tsx
  src/mocks/OrdersMock.tsx
  src/pages/orders-list/OrdersList.tsx
Labels: approved, lgtm

#244 229 order portal into sprint-5
  src/components/__common__/sidebar/nav/main/AdminNavMainData.tsx
  src/components/__common__/sidebar/nav/main/EmployeeNavMainData.tsx
  src/components/home/ApproveDeclineConfirmationDialog.tsx
  src/components/loans/employee/allLoansTable/AllLoanTable.tsx
  src/components/order-table/OrderDropdownMenu.tsx
  src/components/order-table/OrderListColumnDef.tsx
  src/components/order-table/OrderTable.tsx
  src/mocks/OrdersMock.tsx
  src/pages/orders-list/OrdersList.tsx
  src/router/routes.tsx
  src/types/order.ts
Labels: approved, lgtm

#242 Filter table fixed, Option Reset Used Limit fixed
  src/__mocks/mock-actuaries.ts
  src/components/actuary/ActuariesTable.tsx
  src/pages/actuary/ActuaryDropDownMenu.tsx
Labels: size/L, approved, lgtm

#247 Issue #227: Actuaries data tabl
  src/__mocks/mock-actuaries.ts
  src/api/actuary.ts
  src/components/__common__/sidebar/AppSidebar.tsx
  src/components/__common__/sidebar/nav/main/AdminNavMainData.tsx
  src/components/__common__/sidebar/nav/main/EmployeeNavMainData.tsx
  src/components/actuary/ActuariesListColumnDef.tsx
  src/components/actuary/ActuariesTable.tsx
  src/components/actuary/edit-actuary/EditActuaryDialog.tsx
  src/components/actuary/edit-actuary/EditActuaryForm.tsx
  src/components/actuary/reset-used-limit/ResetLimitConfirmDialog.tsx
  src/pages/actuary/ActuaryDropDownMenu.tsx
  src/pages/actuary/ActuaryListPage.tsx
  src/router/routes.tsx
  src/types/actuary.ts
Labels: approved, lgtm, size/XL

#248 Sprint 5 finalizing: Bug fixes and Improvements
  src/components/__common__/Footer.tsx
  src/components/__common__/sidebar/AppSidebar.tsx
  src/components/__common__/sidebar/nav/main/AdminNavMainData.tsx
  src/components/__common__/sidebar/nav/main/EmployeeNavMainData.tsx
  src/components/__common__/sidebar/nav/main/NavMain.tsx
  src/components/actuary/edit-actuary/EditActuaryForm.tsx
  src/components/securities/SecurityCreateOrder.tsx
  src/components/securities/SecurityDetails.tsx
  src/components/securities/SecurityListCard.tsx
  src/pages/securities/Security.tsx
  src/router/routes.tsx
Labels: size/L, approved, lgtm

#249 [STYLING] Minor styling improvements
  src/components/home/RecentTransactions.tsx
  src/components/securities/SecurityCreateOrder.tsx
  src/components/securities/SecurityFIlters.tsx
  src/lib/transactions-table-utils.tsx
Labels: approved, lgtm, size/M, styling

#256 Issue #255 Rename Securities to Trading
  src/components/__common__/Footer.tsx
  src/components/__common__/sidebar/AppSidebar.tsx
  src/components/__common__/sidebar/nav/main/AdminNavMainData.tsx
  src/components/__common__/sidebar/nav/main/ClientNavMainData.tsx
  src/components/__common__/sidebar/nav/main/EmployeeNavMainData.tsx
  src/components/__common__/sidebar/nav/main/NavMain.tsx
  src/components/securities/SecurityFIlters.tsx
  src/components/ui/sidebar.tsx
  src/index.css
  src/pages/home/RoleBasedHome.tsx
  src/router/routes.tsx
Labels: size/L, approved, lgtm

#258 Zavrsene tacke 2.2 i 2.3
  src/components/tax/CollectConfirmationDialog.tsx
  src/components/tax/TaxDropdownMenu.tsx
  src/components/tax/TaxListColumnDef.tsx
  src/components/tax/TaxTable.tsx
Labels: size/L, approved, lgtm

#259 Exchanges page admin
  src/api/exchange.ts
  src/components/__common__/ConfirmationDialog.tsx
  src/components/__common__/sidebar/nav/main/AdminNavMainData.tsx
  src/components/bank-account/bank-account-single/TransactionsDataTableColumnDef.tsx
  src/components/exchange-table/ConfirmationText.tsx
  src/components/exchange-table/ExchangeTable.tsx
  src/components/exchange-table/ExchangesListColumnsDef.tsx
  src/lib/format-date.ts
  src/mocks/mokdatasExchange.tsx
  src/pages/exchanges/Exchanges.tsx
  src/router/routes.tsx
  src/types/exchange.ts
Labels: approved, lgtm, size/XL
