Repository RAF-SI-2024/Banka-2-Frontend, pull requests merged in 2025-04, with the labels that each got.

#260 My portfolio
  package-lock.json
  src/components/__common__/sidebar/nav/main/ClientNavMainData.tsx
  src/components/home/ConverterCard.tsx
  src/components/portfolio/PortfolioTable.tsx
  src/components/portfolio/PortfolioTableCard.tsx
  src/components/portfolio/PortfolioTableColumns.tsx
  src/components/portfolio/TaxCard.tsx
  src/components/portfolio/TotalProfitCard.tsx
  src/mocks/CurrencyMock.tsx
  src/mocks/PortfolioDataMock.tsx
  src/pages/my-portfolio/MyPortfolioPage.tsx
  src/router/routes.tsx
  src/types/portfolio-data.ts
Labels: approved, lgtm, size/XL

#261 Issue #254: Security details page
  package.json
  pnpm-lock.yaml
  src/assets/Logo.png
  src/components/__common__/header/HeaderWithThemeSwitch.tsx
  src/components/order-table/OrderListColumnDef.tsx
  src/components/securities/SecurityGraph.tsx
  src/components/securities/SecurityInfiniteList.tsx
  src/components/securities/SecurityListCard.tsx
  src/components/trading/ChartUtils.tsx
  src/components/trading/CreateOrderFormDef.tsx
  src/components/trading/SecurityCreateOrder.tsx
  src/components/trading/SecurityDetails.tsx
  src/components/trading/SecurityFIlters.tsx
  src/components/trading/SecurityGraph.tsx
  src/components/trading/SecurityInfiniteList.tsx
  src/components/trading/SecurityListCard.tsx
  src/components/trading/SecurityListSingle.tsx
  src/components/trading/SecurityTradingTable.tsx
  src/components/trading/TradingViewChart.tsx
  src/components/ui/dropdown-menu.tsx
  src/index.css
  src/layouts/SecurityLayout.tsx
  src/mocks/trading/GraphMock.tsx
  src/mocks/trading/SecurityListMock.tsx
  src/pages/securities/Security.tsx
  src/pages/trading/Trading.tsx
  src/router/routes.tsx
  src/types/security.ts
Labels: approved, lgtm, size/XXL

#266 docker setup
  .dockerignore
  Dockerfile
  nginx.conf
Labels: approved, lgtm, size/M

#267 Timescale buttons & styling improvements
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/assets/PortfolioDown.tsx
  src/assets/PortfolioUp.tsx
  src/components/__common__/Loader.tsx
  src/components/__common__/error/ErrorAlert.tsx
  src/components/__common__/error/ErrorFallback.tsx
  src/components/portfolio/PortfolioTableCard.tsx
  src/components/portfolio/TaxCard.tsx
  src/components/portfolio/TotalProfitCard.tsx
  src/components/trading/SecurityGraph.tsx
  src/components/trading/SecurityInfiniteList.tsx
  src/components/trading/SecurityListCard.tsx
  src/components/trading/TradingViewChart.tsx
  src/mocks/trading/GraphMock.tsx
  src/pages/my-portfolio/MyPortfolioPage.tsx
  src/pages/trading/Trading.tsx
  src/style/Loader.css
Labels: approved, lgtm, size/XXL

#269 matchin transaction response from backend cause it was changed
  src/components/payments/payment-new/NewPaymentForm.tsx
  src/components/payments/payment-new/NewPaymentFormDef.tsx
  src/components/payments/transfer-new/NewTransferForm.tsx
  src/components/payments/transfer-new/NewTransfertFormDef.tsx
  src/lib/transactions-table-utils.tsx
  src/types/bank-account.ts
  src/types/transaction.ts
Labels: approved, lgtm, size/M

#270 Sprint 7 done
  .gitignore
  Dockerfile
  cypress.config.ts
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/api/currency_exchange.ts
  src/api/exchange.ts
  src/assets/PortfolioDown.tsx
  src/assets/PortfolioUp.tsx
  src/components/__common__/Loader.tsx
  src/components/__common__/error/ErrorAlert.tsx
  src/components/__common__/error/ErrorFallback.tsx
  src/components/exchange-table/ExchangeTable.tsx
  src/components/payments/exchange-rate-list/ExchangeRateListTable.tsx
  src/components/payments/payment-new/NewPaymentForm.tsx
  src/components/payments/payment-new/NewPaymentFormDef.tsx
  src/components/payments/transfer-new/NewTransferForm.tsx
  src/components/payments/transfer-new/NewTransfertFormDef.tsx
  src/components/portfolio/PortfolioTableCard.tsx
  src/components/portfolio/TaxCard.tsx
  src/components/portfolio/TotalProfitCard.tsx
  src/components/trading/SecurityGraph.tsx
  src/components/trading/SecurityInfiniteList.tsx
  src/components/trading/SecurityListCard.tsx
  src/components/trading/TradingViewChart.tsx
  src/context/AuthContext.tsx
  src/hooks/useAuth.ts
  src/lib/transactions-table-utils.tsx
  src/mocks/trading/GraphMock.tsx
  src/pages/my-portfolio/MyPortfolioPage.tsx
  src/pages/trading/Trading.tsx
  src/style/Loader.css
  src/types/bank-account.ts
  src/types/currency_exchange.ts
  src/types/exchange.ts
  src/types/transaction.ts
  start-frontend.bat
  start-frontend.sh
  tsconfig.app.json
  tsconfig.node.json
Labels: approved, lgtm, size/XXL

#271 Transactions | fix showing transactions
  src/lib/transactions-table-utils.tsx
  src/pages/bank-accounts-client/BankAccount.tsx
  src/types/transaction.ts
Labels: approved, lgtm, size/M

#273 Sprint 8 done
  cypress/support/commands/employee/bank-account-list.ts
  src/api/card.ts
  src/api/loan.ts
  src/api/transaction.ts
  src/components/card/card-single/BankCardDetails.tsx
  src/hooks/sidebar/use-credit-cards-data.ts
  src/lib/transactions-table-utils.tsx
  src/pages/bank-accounts-client/BankAccount.tsx
  src/types/transaction.ts
Labels: size/L, approved, lgtm

#276 Issue #275: Fix CORS policy error
  src/api/axios.ts
  src/api/bank_user/actuary.ts
  src/api/bank_user/auth.ts
  src/api/bank_user/bank-account.ts
  src/api/bank_user/card.ts
  src/api/bank_user/currency.ts
  src/api/bank_user/transaction.ts
  src/api/bank_user/transactionCode.ts
  src/api/bank_user/user.ts
  src/components/user-table/all-users/UserTable.tsx
Labels: size/L, approved, lgtm

#280 Issue #278: Stocks API integration + Minor fixes
  cypress/e2e/employee/scenario1.cy.ts
  cypress/support/commands.ts
  cypress/support/commands/employee/bank-account-list.ts
  cypress/support/index.d.ts
  src/api/axios.ts
  src/api/bank_user/auth.ts
  src/api/exchange/exchange.ts
  src/api/exchange/security.ts
  src/components/__common__/EmailConfirmation.tsx
  src/components/__common__/sidebar/nav/main/AdminNavMainData.tsx
  src/components/card/card-create/CreateCardForm.tsx
  src/components/exchange-table/ExchangeTable.tsx
  src/components/exchange-table/ExchangesListColumnsDef.tsx
  src/components/loans/employee/requestTable/LoanRequestTable.tsx
  src/components/payments/payment-new/AddRecipientTemplate.tsx
  src/components/register/client/RegisterFormSecondClient.tsx
  src/components/trading/SecurityInfiniteList.tsx
  src/components/trading/SecurityListSingle.tsx
  src/components/user-table/all-users/edit-user/EditUserDialog.tsx
  src/mocks/mokdatasExchange.tsx
  src/mocks/trading/SecurityListMock.tsx
  src/pages/trading/Trading.tsx
  src/router/routes.tsx
  src/types/exchange/exchange.ts
  src/types/exchange/security.ts
  src/types/exchange/stock.ts
Labels: size/L, approved, lgtm

#281 Cards | fix showing cards for each client
  src/api/bank_user/card.ts
Labels: size/XS, approved, lgtm

#282 Sprint 9 done
  cypress/e2e/employee/scenario1.cy.ts
  cypress/support/commands.ts
  cypress/support/commands/employee/bank-account-list.ts
  cypress/support/index.d.ts
  src/api/axios.ts
  src/api/bank_user/actuary.ts
  src/api/bank_user/auth.ts
  src/api/bank_user/bank-account.ts
  src/api/bank_user/card.ts
  src/api/bank_user/currency.ts
  src/api/bank_user/transaction.ts
  src/api/bank_user/transactionCode.ts
  src/api/bank_user/user.ts
  src/api/exchange/exchange.ts
  src/api/exchange/security.ts
  src/components/__common__/EmailConfirmation.tsx
  src/components/__common__/sidebar/nav/main/AdminNavMainData.tsx
  src/components/card/card-create/CreateCardForm.tsx
  src/components/exchange-table/ExchangeTable.tsx
  src/components/exchange-table/ExchangesListColumnsDef.tsx
  src/components/loans/employee/requestTable/LoanRequestTable.tsx
  src/components/payments/payment-new/AddRecipientTemplate.tsx
  src/components/register/client/RegisterFormSecondClient.tsx
  src/components/trading/SecurityInfiniteList.tsx
  src/components/trading/SecurityListSingle.tsx
  src/components/user-table/all-users/UserTable.tsx
  src/components/user-table/all-users/edit-user/EditUserDialog.tsx
  src/mocks/mokdatasExchange.tsx
  src/mocks/trading/SecurityListMock.tsx
  src/pages/trading/Trading.tsx
  src/router/routes.tsx
  src/types/exchange/exchange.ts
  src/types/exchange/security.ts
  src/types/exchange/stock.ts
Labels: approved, lgtm

#283 Transaction fix (toCurrencyId)
  src/api/axios.ts
  src/api/bank_user/transactionCode.ts
  src/components/payments/payment-new/NewPaymentForm.tsx
  src/components/payments/payment-new/NewPaymentFormDef.tsx
  src/lib/transactions-table-utils.tsx
Labels: size/L, approved, lgtm

#285 Testing | User Management test done
  cypress/e2e/admin/user-management.cy.ts
  cypress/support/commands/admin/user-management.ts
  cypress/support/e2e.ts
  src/components/user-table/all-users/UserDropdownMenu.tsx
Labels: approved, lgtm

#287 Issue #284: Multi-Currency support
  src/components/__common__/RadialChart.tsx
  src/components/bank-account/bank-account-single/BankAccountBalance.tsx
  src/components/payments/payment-new/NewPaymentForm.tsx
  src/components/payments/payment-new/NewPaymentFormDef.tsx
  src/components/payments/transfer-new/NewTransferForm.tsx
  src/components/payments/transfer-new/NewTransfertFormDef.tsx
  src/index.css
  src/types/bank_user/bank-account.ts
Labels: approved, lgtm, size/XL

#288 Testing | Transactions - transactions and transfers
  cypress.config.ts
  cypress/e2e/client/transactions.cy.ts
  cypress/e2e/employee/scenario1.cy.ts
  src/components/bank-account/bank-account-create/CreateBankAccount.tsx
  src/components/payments/payment-new/NewPaymentForm.tsx
  src/components/payments/payment-new/RecipientInput.tsx
  src/components/payments/transfer-new/NewTransferForm.tsx
Labels: size/L, approved, lgtm

#289 Permissions | Agent and Supervisor permissions.
  src/__mocks/mock-actuaries.ts
  src/components/__common__/sidebar/AppSidebar.tsx
  src/components/__common__/sidebar/nav/main/AdminNavMainData.tsx
  src/components/__common__/sidebar/nav/main/EmployeeNavMainData.tsx
  src/components/actuary/ActuariesListColumnDef.tsx
  src/components/actuary/edit-actuary/EditActuaryForm.tsx
  src/pages/actuary/ActuaryDropDownMenu.tsx
  src/types/bank_user/actuary.ts
Labels: size/L, approved, lgtm
